6 essayer de transmettre une trame test
Wakayo-Quozorox/SACS pull request #13
Opened 2023-06-01 15:40 UTC by hmnz

2023-06-01 17:54 UTC, Wakayo-Quozorox commented on Arduino/Rx_node_I/desktop.ini
Ça devrait pas être là comme fichier je pense

2023-06-01 17:59 UTC, Wakayo-Quozorox requested changes
@hmnz Est-ce que tu peux enlever les .ini et ajouter *.ini au gitignore déjà pour commencer ? Soumet une nouvelle request et je valide tout ça demain !

2023-06-01 17:59 UTC, Wakayo-Quozorox commented on Arduino/TX_node_I/desktop.ini
À supprimer !

2023-06-01 17:59 UTC, Wakayo-Quozorox commented on Arduino/Rx_node_I/desktop.ini
À supprimer ! Et ajouter *.ini dans le gitignore si possible !

2023-06-01 21:53 UTC, Wakayo-Quozorox commented on Arduino/Rx_node_I/Rx_node_I.ino
À propos des valeurs en define, l'usage veut qu'on mette le nom des valeurs en MAJUSCULE parce que c'est pas des variables. Je sais qu'en arduino on fait un peu à la sauce de ce qui est fait, et je sais pas si c'était comme ça de base dans le truc, mais pour tout ce qui est redéfini à la main par nous mêmes ce serait bien que ça soit fait en MAJ.

2023-06-01 21:56 UTC, Wakayo-Quozorox commented on Arduino/Rx_node_I/sx1272_INSAT.cpp
@hmnz Est-ce que tu as fait des modifications dans ce fichier et son fichier d'en-tête ?

2023-06-01 22:01 UTC, Wakayo-Quozorox commented on STM32/app/src/appSX1272.c
> +    LgMsg=sizeof(Message) / sizeof(Message[0]);
@hmnz sizeof(Message) ça marche comme ça ? C'est super bizarre, message c'est un pointeur non ?

2023-06-02 07:06 UTC, hmnz commented on Arduino/Rx_node_I/Rx_node_I.ino
Oui je suis daccord, à noter dans les bonnes pratiques d'ailleurs @leilamedina

2023-06-02 07:07 UTC, hmnz commented on Arduino/Rx_node_I/sx1272_INSAT.cpp
Nop

2023-06-02 07:08 UTC, hmnz commented on Arduino/Rx_node_I/sx1272_INSAT.cpp
Je l'ai juste épluché pour vérifier que tout est réglo et c'est good

2023-06-02 07:12 UTC, hmnz commented on STM32/app/src/appSX1272.c
> +    LgMsg=sizeof(Message) / sizeof(Message[0]);
Quand on travaillait avec des chaines de caractères on utilisait strlen mais du coup j'avais un warning après le changement de type. Je me suis renseigné pour savoir comment récupérer la taille d'un tableau et ce qui est ressorti est qu'il faut diviser la taille totale du tableau `sizeof(Message)` par la taille d'un élément du tableau `sizeof(Message[0])`. Ca nous donne bien 12 ici. @Wakayo-Quozorox  Si connais un autre moyen de faire ça dis moi.

2023-06-02 07:21 UTC, hmnz commented on STM32/app/src/appSX1272.c
> +    LgMsg=sizeof(Message) / sizeof(Message[0]);
Ca marche que en statique par contre, aucune idée de comment faire en dynamique. On peut aussi le rentrer en brut dans le sens où quand quelqu'un va envoyer une trame il connaitra la taille de sa trame. La seule question est de savoir pour la réception : dans le code récepteur il faut aussi une taille `LgMsg` et je pige pas trop ce qu'elle fait.
Pour l'instant je pense qu'on peut commencer par un truc comme ça et ouvrir une autre issue spécifique à ça

2023-06-02 08:12 UTC, Wakayo-Quozorox approved these changes
Je valide les modifications pour ma part, l'issue #14 a été créé au cas où pour se souvenir que si on rencontre un problème plus tard ça peut venir de là.

2023-06-02 11:49 UTC, leilamedina approved these changes

2023-06-02 14:10 UTC, merged